menu:
  Home: /
  Archives: /archives
  About: /about

excerpt_link: Read More
archive_yearly: false

widgets:
  - recent_posts
  - category
  #- tag
  - tagcloud
  #- blogroll

blogrolls:

fancybox: true

duoshuo_shortname: 

google_analytics:
rss:
